services:
  mysql:
    image: mysql:9
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - mysql:/var/lib/mysql
    healthcheck:
      test: "/usr/bin/mysql --user=user --password=pass -e 'SHOW DATABASES;'"
      interval: 5s
      timeout: 5s
      retries: 10


volumes:
  mysql: